name: Counter-App-Pipeline

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create PEM
        run: |
          echo "${{ secrets.secret_key }}" > Deva_key.pem
          chmod 400 Deva_key.pem

      - name: Copy files
        run: |
          scp -o StrictHostKeyChecking=no -i Deva_key.pem app.py ec2-user@13.235.99.166:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i Deva_key.pem requirements.txt ec2-user@13.235.99.166:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i Deva_key.pem Dockerfile ec2-user@13.235.99.166:/home/ec2-user/
          scp -o StrictHostKeyChecking=no -i Deva_key.pem count.txt ec2-user@13.235.99.166:/home/ec2-user/

      - name: Deploy Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i Deva_key.pem ec2-user@13.235.99.166 "
          sudo docker stop counter-app || true &&
          sudo docker rm counter-app || true &&
          sudo docker build -t counter-app /home/ec2-user &&
          sudo docker run -d -p 5001:5000 --name counter-app counter-app
          "
